---
- name: install and start apache HTTPD
  hosts: uos1
  become: yes

  tasks:
 ######   
    - name: Webserver Part - install and start Apache HTTPD
      apt: 
        name: apache2
        state: present
        #update_cache: yes
    - name: correct index.html is present
      copy: 
        src: files/index.html
        dest: /var/www/html/index.html

#######
    - name: DB Part - installing mariadb
      apt: 
        name: "{{ item }}"
        state: latest
      loop:
        - mariadb-common
        - mariadb-server
        - mariadb-client
    - name: installing pip version 3
      apt:
        name: python3-pip
        state: present
    - name: pip3 install part of mariadb
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-pymysql
    - name: configure mariadb
      template: 
        src: ./template/my.cnf.j2
        dest: /etc/mysql/my.cnf
        owner: root
        mode: 0600
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started

 #######
    - name: installation of PHP 7.3.X 
      apt:
        name: 
        - php
        - libapache2-mod-php 
        - php-mysql
        - php-xml 
        - php-mbstring
        - software-properties-common
        - phpmyadmin
        - php-pdo
        - php-gd
        - php-mbstring
        - php-xml                                                                              
        - php-intl
        - wget
        - texlive
    - name: download MediaWIKI
      get_url: 
        url: http://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz
        dest: /tmp/mediawiki.tgz
    - name: unarchive MediaWIKI
      ansible.builtin.unarchive: 
        src: /tmp/mediawiki.tgz
        dest: /tmp
        remote_src: yes
        owner: root
        group: root
    - name: moving MediaWIKI from tmp to web directory
      command: mv/tmp/mediawiki-1.34.2/* /var/www/html/
 
  handlers:
    - name: httpd is reloaded
      service:
        name: apache2
        state: reloaded
    - name: restarting httpd
      service:
        name: apache2
        state: restarted
        enabled: true
    - name: start MySQL service
      service:
        name: mariadb
        state: started
        enabled: true
